variable "cilium_version" {}
variable "flatcar_version" {}
variable "keepalived_version" {}
variable "kubernetes_config_version" {}
variable "kubernetes_ha_ip" {}
variable "kubernetes_version" {}
variable "matchbox_ca_crt" {}
variable "matchbox_client_crt" {}
variable "matchbox_client_key" {}
variable "matchbox_http_endpoint" {}
variable "matchbox_ip" {}
variable "matchbox_rpc_endpoint" {}
variable "ssh_authorized_key" {}
