variable "cilium_version" {}
variable "flatcar_version" {}
variable "keepalived_version" {}
variable "kubernetes_ca_crt_hash_path" {}
variable "kubernetes_ca_crt_path" {}
variable "kubernetes_ca_key_path" {}
variable "kubernetes_config_version" {}
variable "kubernetes_ha_ip" {}
variable "kubernetes_version" {}
variable "matchbox_ca_crt_path" {}
variable "matchbox_client_crt_path" {}
variable "matchbox_client_key_path" {}
variable "matchbox_http_endpoint" {}
variable "matchbox_rpc_endpoint" {}
variable "ssh_authorized_key" {}
