variable "flatcar_channel" {}
variable "flatcar_network_ip_address" {}
variable "flatcar_network_ip_dhcp_ranges_end" {}
variable "flatcar_network_ip_dhcp_ranges_start" {}
variable "flatcar_network_ip_netmask" {}
variable "flatcar_network_mode" {}
variable "flatcar_network_name" {}
variable "flatcar_network_nat_ports_end" {}
variable "flatcar_network_nat_ports_start" {}
variable "flatcar_version" {}
variable "matchbox_ca_crt_path" {}
variable "matchbox_cidr" {}
variable "matchbox_dns_servers" {}
variable "matchbox_gateway" {}
variable "matchbox_ip" {}
variable "matchbox_server_crt_path" {}
variable "matchbox_server_key_path" {}
