variable "disk_capacity_bytes" {}
variable "flatcar_channel" {}
variable "ca_certificate" {}
variable "server_certificate" {}
variable "server_private_key" {}
variable "flatcar_release" {}
variable "memory" {}
variable "vcpu" {}
variable "vm_name" {}